# Generated by Django 6.0.2 on 2026-02-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20260222_1030'),
        ('store', '0002_rename_first_name_customer_given_name'),
    ]

    operations = [
    ]
