# Generated by Django 6.0.2 on 2026-02-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_merge_20260224_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
