# Generated by Django 6.0.2 on 2026-02-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_given_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='featured_Product',
            new_name='featured_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Inventory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Promotion',
            new_name='promotions',
        ),
    ]
